### ISSUE TITLE
setup.py url 주소가 redirect 됩니다.

### ISSUE THREAD

**Issue by lovit** [hank110/bagofconcepts#3]
현재 setup.py 파일에 ` url = 'https://github.com/hank110/boc'` 로 설정되어 있는데, hank110/bagofconcepts 로 redirect 됩니다. 이왕이면 그 주소로 적는게 더 좋을 것 같습니다.

**Comment by hank110** [comment]
url 주소 수정되었습니다. 감사합니다.
